### ISSUE TITLE
osbs build fails with build_type prod-without-koji

### ISSUE THREAD

**Issue by pbabinca** [DBuildService/osbs#64]
```
$ git log --oneline -1
b537db4 (HEAD, upstream/master, master) Merge pull request #61 from DBuildService/python3-parse-headers
$ cat ./osbs.conf
[default]
openshift_uri = http://127.0.0.1:9443/
sources_command = some_command sources
registry_uri = docker-registry.example.com
verify_ssl = 0
use_kerberos = false
metadata_plugin_use_auth = 0
vendor = Foo vendor
authoritative_registry = registry.example.com
build_type = prod-without-koji
build_host = buildhost.example.com
$ osbs --verbose --config ./osbs.conf build -c docker-hello-world -a x86_64 -u pbabinca --git-commit master -g 'git://github.com/TomasTomecek/docker-hello-world?#master' --build-json-dir ./inputs/
```
```
2015-05-12 13:51:18,179 - osbs - DEBUG - Logging level set to debug
Traceback (most recent call last):
  File "/home/pbabinca/.virtualenvs/osbs/bin/osbs", line 9, in <module>
    load_entry_point('osbs==0.3', 'console_scripts', 'osbs')()
  File "/home/pbabinca/workspace/osbs/osbs/cli/main.py", line 311, in main
    args.func(args, osbs)
  File "/home/pbabinca/workspace/osbs/osbs/cli/main.py", line 131, in cmd_build
    namespace=args.namespace,
  File "/home/pbabinca/workspace/osbs/osbs/api.py", line 27, in catch_exceptions
    return func(*args, **kwargs)
  File "/home/pbabinca/workspace/osbs/osbs/api.py", line 190, in create_build
    return self.create_prod_without_koji_build(namespace=namespace, **kwargs)
  File "/home/pbabinca/workspace/osbs/osbs/api.py", line 27, in catch_exceptions
    return func(*args, **kwargs)
TypeError: create_prod_without_koji_build() got an unexpected keyword argument 'target'
````

**Comment by TomasTomecek** [comment]
Resolved by https://github.com/DBuildService/osbs/commit/abcc73fb54bb1995a0d02040a0f9a2e6085a14f4
