### ISSUE TITLE
handle closing of curl multi properly when it doesn't have any handles

### ISSUE THREAD

**Issue by TomasTomecek** [DBuildService/osbs#84]
When first request of curl multi fails, there are no handles and calling `close_multi` will raise TB.

```
Traceback (most recent call last):
  File "/home/user/.virtualenvs/asd/bin/osbs", line 9, in <module>
    load_entry_point('osbs==0.4', 'console_scripts', 'osbs')()
  File "/home/user/workspace/osbs/osbs/cli/main.py", line 309, in main
    args.func(args, osbs)
  File "/home/user/workspace/osbs/osbs/cli/main.py", line 153, in cmd_build_logs
    logs = osbs.get_build_logs(build_id, follow=False, namespace=args.namespace)
  File "/home/user/workspace/osbs/osbs/api.py", line 39, in catch_exceptions
    raise OsbsException(cause=ex, traceback=sys.exc_info()[2])
osbs.exceptions.OsbsException: AttributeError("'NoneType' object has no attribute 'remove_handle'",)
 
Original traceback (most recent call last):
  File "/home/user/workspace/osbs/osbs/api.py", line 28, in catch_exceptions
    return func(*args, **kwargs)
  File "/home/user/workspace/osbs/osbs/api.py", line 218, in get_build_logs
    return self.os.logs(build_id, follow=False, namespace=namespace)
  File "/home/user/workspace/osbs/osbs/core.py", line 185, in logs
    response.close_multi()
  File "/home/user/workspace/osbs/osbs/http.py", line 243, in close_multi
    self.curl_multi.remove_handle(self.curl)
AttributeError("'NoneType' object has no attribute 'remove_handle'",)
```

found by @pbabinca

**Comment by TomasTomecek** [comment]
Fixed by https://github.com/DBuildService/osbs/commit/dd842a98acc1e4d26699cc908dedc9a3fe8b86d1
